# Generated by Django 3.0.9 on 2020-08-10 09:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0002_auto_20200810_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket', name='uuid', field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='basketproductrelation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
