# Generated by Django 3.0.9 on 2020-08-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baskets', '0003_auto_20200810_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproductrelation', name='quantity', field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
